# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Update mix packages
  - package-ecosystem: "mix"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"

  # Update github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update js packages
  - package-ecosystem: "npm"
    directory: "/api_docs"
    schedule:
      interval: "weekly"
